<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><IsPackable>false</IsPackable><EnableContainer>true</EnableContainer><ContainerRepository>eventstore</ContainerRepository></PropertyGroup>
  <ItemGroup><ProjectReference Include="../Hexalith.Platform.Identity/Hexalith.Platform.Identity.csproj" /></ItemGroup>
</Project>
